import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Utilities/Navbar/NAVBAR JEMBODDDDD"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const gricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-rotesque",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={gricolageGrotesque.className}>
      <body
        className={`antialiased`}
      >
        <Navbar className="fixed"></Navbar>
        {children}
      </body>
    </html>
  );
}
